version: "3.9"
services:
  web:
    image: "localhost/web:latest"
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ${HOME}/data/gg:/data
      - ${HOME}/repos/guardgraph:/code
    environment:
      FLASK_APP: "guardgraph"
  neo4j:
    image: "neo4j:5.7.0"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_server_config_strict__validation_enabled: "false"
    volumes:
      - ${HOME}/data/gg:/data
      - ${HOME}/data/gg/neo4j_import:/var/lib/neo4j/import
#  gis:
#    image: "localhost/gis:latest"
#    build: ./containers/gis
#    volumes:
#      - ${HOME}/data/gg:/data
#      - ${HOME}/repos/guardgraph:/code
