version: "3.9"
services:
  web:
    image: "localhost/web:latest"
    build: .
    ports:
      - 8000:5000
    volumes:
      - ${HOME}/data/gg:/data
      - ${HOME}/data/worker:/mbg/instance/shared
      - ${HOME}/repos/guardgraph:/code
    environment:
      FLASK_APP: "guardgraph"
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      NEO4J_CREDENTIAL: ${NEO4J_CREDENTIAL}
      #MARIADB_PASSWORD: ${MARIADB_CREDENTIAL}
    depends_on:
      neo4j:
        condition: service_started
  init-web:
    image: "localhost/web:latest"
    build: .
    command: 'sleep 10 && guardgraph-init'
    volumes:
      - ${HOME}/data/gg:/data
      - ${HOME}/repos/guardgraph:/code
      - ${HOME}/data/worker:/mbg/instance/shared
    environment:
      FLASK_APP: "guardgraph"
      #MARIADB_PASSWORD: ${MARIADB_CREDENTIAL}
  rabbitmq:
    image: rabbitmq:3-management-alpine
    command: ash -c "echo 'log.console.level = warning'
      >>/etc/rabbitmq/conf.d/10-default-guest-user.conf && rabbitmq-server"
    ports:
      - 5672:5672
      - 15672:15672
  worker:
    image: "localhost/web:latest"
    depends_on:
      - rabbitmq
      - web
    command: celery -A guardgraph.celery_app worker --loglevel INFO --concurrency=4
    volumes:
      - ${HOME}/data/gg:/data
      - ${HOME}/data/worker:/mbg/instance/shared
      - ${HOME}/repos/guardgraph:/code
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      NEO4J_CREDENTIAL: ${NEO4J_CREDENTIAL}
      #MARIADB_PASSWORD: ${MARIADB_CREDENTIAL}
  init-neo4j:
    image: "neo4j:5.7.0"
    command: "true" #neo4j-admin database import full --delimiter='\t' --array-delimiter="|" --quote='"' --nodes=import/globi_nodes.tsv.gz --relationships=import/globi_merged_edges.tsv.gz --overwrite-destination neo4j
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_server_config_strict__validation_enabled: "false"
    volumes:
      - ${HOME}/data/gg:/data
      - ${HOME}/data/gg/neo4j_import:/var/lib/neo4j/import
    depends_on:
      init-web:
        condition: service_completed_successfully
  neo4j:
    image: "neo4j:5.7.0"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_server_config_strict__validation_enabled: "false"
    volumes:
      - ${HOME}/data/gg:/data
      - ${HOME}/data/gg/neo4j_import:/var/lib/neo4j/import
    depends_on:
      init-neo4j:
        condition: service_completed_successfully
  #db:
  #  image: mariadb:latest
  #  ports:
  #    - 3306:3306
  #  environment:
  #    MARIADB_ROOT_PASSWORD: ${MARIADB_CREDENTIAL}
  #    MARIADB_PASSWORD: ${MARIADB_CREDENTIAL}
  #    MARIADB_USER: guardin
  #    MARIADB_DATABASE: guardin
